### ISSUE TITLE
Error Setting up First Cluster

### ISSUE THREAD

**Issue by albinblaschka** [datalyze-solutions/QgisMarkerCluster#3]
Hello!
What I did:
* Opened QGIS 2.6 on Windows 7
* Activated the plugin
* Clicked on the button to load the demo data ("Load Point Layer")
* Clicked on the button "Setup first cluster"

The following error message appears:

Traceback (most recent call last):
  File "C:/Users/blaschka/.qgis2/python/plugins\QgisMarkerCluster\libs\QgsClusterLayer.py", line 553, in updateClusters
    self.buildCluster(zoomlevel, distance=None, pixelSize=pixelSize)
  File "C:/Users/blaschka/.qgis2/python/plugins\QgisMarkerCluster\libs\QgsClusterLayer.py", line 478, in buildCluster
    self.buildClusterGeometry()
  File "C:/Users/blaschka/.qgis2/python/plugins\QgisMarkerCluster\libs\QgsClusterLayer.py", line 504, in buildClusterGeometry
    feature.setAttribute("count", cluster.count)
KeyError: 'count'

Python-Version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

Plattform: Win 7, QGIS 2.6.0

What could it be? Did I something wrong?
Greetings from Austria
Albin

**Comment by albinblaschka** [comment]
P.S.: After some fiddling and trial & error, I was able to make it work - the solution is quite simple:

I had to create the tmp-folder manually below ~\.qgis2\python\plugins\QgisMarkerCluster\tmp
It seems this tmp-folder is not created when missing/during install/with the first run of the plugin...
Albin

**Comment by kaotika** [comment]
The writing algorithm was very bad...I fixed this in the next release. Now the cluster layers will be written to the users temp directory.

**Comment by albinblaschka** [comment]
Thanks! It is a very useful plugin, btw :-)
